# Generated by Django 5.2.5 on 2025-09-18 08:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=10, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('journey_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting List'), ('RAC', 'RAC'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_tickets', to='mainApp.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_tickets', to='mainApp.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('UPI', 'UPI'), ('WALLET', 'Digital Wallet')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('gateway_response', models.TextField(blank=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='mainApp.ticket')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('berth_preference', models.CharField(choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('SIDE_LOWER', 'Side Lower'), ('SIDE_UPPER', 'Side Upper'), ('NO_PREFERENCE', 'No Preference')], default='NO_PREFERENCE', max_length=15)),
                ('current_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting List'), ('RAC', 'RAC'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mainApp.ticket')),
            ],
            options={
                'ordering': ['ticket', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('train_type', models.CharField(choices=[('EXPRESS', 'Express'), ('SUPERFAST', 'Superfast'), ('PASSENGER', 'Passenger'), ('RAJDHANI', 'Rajdhani'), ('SHATABDI', 'Shatabdi'), ('DURONTO', 'Duronto')], default='EXPRESS', max_length=20)),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['train_number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='available_seats_not_exceed_total')],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.train'),
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.train')),
            ],
            options={
                'ordering': ['journey_date', 'train'],
                'unique_together': {('train', 'journey_date')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='train_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.trainschedule'),
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_list_number', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.passenger')),
            ],
            options={
                'ordering': ['booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('reservation_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tatkal_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_to', to='mainApp.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_from', to='mainApp.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.train')),
            ],
            options={
                'unique_together': {('train', 'source_station', 'destination_station')},
            },
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('distance_from_source', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_number', models.CharField(blank=True, max_length=5)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='mainApp.train')),
            ],
            options={
                'ordering': ['train', 'sequence_number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('distance_from_source__gte', 0)), name='distance_non_negative')],
                'unique_together': {('train', 'sequence_number')},
            },
        ),
    ]
