# Generated by Django 5.2.7 on 2025-11-02 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination_station',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='journey_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='pnr_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='source_station',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='total_fare',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='train',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='train_schedule',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(default='Passenger', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(editable=False, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='mainApp.trainschedule'),
        ),
    ]
