# Generated by Django 5.2.7 on 2025-11-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_ticket_options_remove_ticket_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SLEEPER', 'Sleeper'), ('AC_3_TIER', 'AC 3 Tier'), ('AC_2_TIER', 'AC 2 Tier'), ('AC_1_TIER', 'AC 1 Tier'), ('FIRST_CLASS', 'First Class')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='mainApp.trainschedule'),
        ),
    ]
