# Generated by Django 5.2.7 on 2025-11-02 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_ticket_seat_class_alter_ticket_pnr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_number', models.CharField(max_length=5)),
                ('coach_type', models.CharField(choices=[('GENERAL', 'General'), ('SLEEPER', 'Sleeper'), ('AC_3_TIER', 'AC 3 Tier'), ('AC_2_TIER', 'AC 2 Tier'), ('AC_1_TIER', 'AC 1 Tier'), ('FIRST_CLASS', 'First Class')], max_length=20)),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='mainApp.train')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='mainApp.coach'),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='coach_available_seats_not_exceed_total'),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('train', 'coach_number')},
        ),
    ]
