# Generated by Django 5.2.7 on 2025-11-06 14:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_coach_passenger_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='berth_preference',
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 6, 14, 3, 45, 330673, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_class',
            field=models.CharField(choices=[('SLEEPER', 'Sleeper'), ('AC_3_TIER', 'AC 3 Tier'), ('AC_2_TIER', 'AC 2 Tier'), ('AC_1_TIER', 'AC 1 Tier'), ('FIRST_CLASS', 'First Class')], default='SLEEPER', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.coach'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='current_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting List'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.UniqueConstraint(condition=models.Q(('seat_number', ''), _negated=True), fields=('coach', 'seat_number'), name='unique_seat_per_coach'),
        ),
    ]
