# Generated by Django 5.2.7 on 2025-11-10 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_passenger_berth_preference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['train', 'coach_number']},
        ),
        migrations.RemoveConstraint(
            model_name='coach',
            name='coach_available_seats_not_exceed_total',
        ),
        migrations.AddField(
            model_name='coach',
            name='available_lower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='available_middle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='available_side_lower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='available_side_upper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='available_upper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='total_lower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='total_middle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='total_side_lower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='total_side_upper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='total_upper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='berth_type',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower Berth'), ('MIDDLE', 'Middle Berth'), ('UPPER', 'Upper Berth'), ('SIDE_LOWER', 'Side Lower Berth'), ('SIDE_UPPER', 'Side Upper Berth')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('SLEEPER', 'Sleeper'), ('AC_3_TIER', 'AC 3 Tier'), ('AC_2_TIER', 'AC 2 Tier'), ('AC_1_TIER', 'AC 1 Tier'), ('FIRST_CLASS', 'First Class')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coach',
            name='total_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
