# Generated by Django 5.2.7 on 2025-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
