# Generated by Django 5.2.7 on 2025-11-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_ticket_booking_status_ticket_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='destination_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_to', to='mainApp.station'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_from', to='mainApp.station'),
        ),
    ]
