# Generated by Django 5.2.7 on 2025-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_ticket_destination_station_ticket_source_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
