# Generated by Django 5.2.7 on 2025-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_ticket_cancellation_reason_ticket_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
