# Generated by Django 5.2.7 on 2025-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_coach_available_seats_trainschedule_base_fare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='available_lower',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='available_middle',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='available_side_lower',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='available_side_upper',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='available_upper',
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('SLEEPER', 'Sleeper'), ('AC_3_TIER', 'AC 3 Tier'), ('AC_2_TIER', 'AC 2 Tier'), ('AC_1_TIER', 'AC 1 Tier'), ('GENERAL', 'General'), ('FIRST_CLASS', 'First Class')], max_length=20),
        ),
    ]
