# Generated by Django 5.2.7 on 2025-11-10 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_coach_options_remove_coach_available_lower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-booking_date']},
        ),
        migrations.RemoveConstraint(
            model_name='passenger',
            name='unique_seat_per_coach',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cancelled_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='berth_type',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('SIDE_LOWER', 'Side Lower'), ('SIDE_UPPER', 'Side Upper')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to='mainApp.coach'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='current_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RAC', 'RAC'), ('WAITING', 'Waiting List'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='seat_class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('WAITING', 'Waiting List')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_tickets', to='mainApp.station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.trainschedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='mainApp.station'),
        ),
    ]
