# Generated by Django 5.2.7 on 2025-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_passenger_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='seat_class',
            field=models.CharField(choices=[('SLEEPER', 'Sleeper'), ('AC_3_TIER', 'AC 3 Tier'), ('AC_2_TIER', 'AC 2 Tier'), ('AC_1_TIER', 'AC 1 Tier'), ('GENERAL', 'General'), ('FIRST_CLASS', 'First Class')], max_length=20),
        ),
    ]
